# This config file overrides _config.yml for developmnet environment

baseurl: /medicamentalia # the subpath of your site, e.g. /blog
url: https://correctiv.github.io                  # the base hostname & protocol for your site
assetsurl: https://correctiv.github.io/medicamentalia/assets
